name: generate snake animation

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch: {}
  push:
    branches:
      - master
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: generate snake svg
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake-neon.svg?color_snake=%233b899a&color_dots=%23000116,%23002847,%23095b79,%2373a09d,%23a47451

      - name: push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
